server:
  port: 8002


eureka:
  instance:
    prefer-ip-address: true #可以显示ip
    #实例的id，默认值为：${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}},也就是：主机名：应用名：应用端口
    instance-id: eureka-client-8002
  client:
    registerWithEureka: true #默认为true，表示要向注册中心注册自己。
    fetchRegistry: true  #默认为true，表示并需要去注册中心检索已经注册的服务
    serviceUrl:
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eurekaserver7001.com:7001/eureka/,http://eurekaserver7002.com:7002/eureka/,http://eurekaserver7003.com:7003/eureka/


spring:
  application:
    name: eureka-client #微服务的名称
